-- CreateTable
CREATE TABLE "Place" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isShowInMap" BOOLEAN NOT NULL DEFAULT true,
    "hasCustomIcon" BOOLEAN NOT NULL DEFAULT false,
    "customIconName" TEXT,
    "lat" DOUBLE PRECISION NOT NULL,
    "lng" DOUBLE PRECISION NOT NULL,
    "schedules" TEXT,
    "phone" TEXT,
    "whatsapp" TEXT,
    "photoUrl" TEXT,
    "web" TEXT,
    "instagram" TEXT,
    "facebook" TEXT,
    "videoLink" TEXT,
    "hasFood" BOOLEAN NOT NULL DEFAULT false,
    "hasShow" BOOLEAN NOT NULL DEFAULT false,
    "hasGames" BOOLEAN NOT NULL DEFAULT false,
    "hasSupervision" BOOLEAN NOT NULL DEFAULT false,
    "categories" TEXT[],
    "ageRanges" TEXT[],
    "description" TEXT,
    "iconType" TEXT,
    "bgColor" TEXT,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Place_pkey" PRIMARY KEY ("id")
);
